name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Setup Maven with OAuth token
      - name: Setup Maven with OAuth
        uses: curityio/curity-maven-gh-action@v1
        with:
          client-secret: ${{ secrets.CURITY_CLI_CLIENT_SECRET }}

      - name: Run tests
        run: mvn verify
